"""
Report generation module for Stockly.
Handles PDF creation with proper table formatting for sales and inventory reports.
"""

from datetime import datetime
from io import BytesIO
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter, A4
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
import mysql.connector


class ReportGenerator:
    """Generate PDF reports for sales and inventory data."""

    def __init__(self, db_connection_func):
        """
        Args:
            db_connection_func: Function that returns a DB connection
        """
        self.get_db_connection = db_connection_func

    def get_year_for_month(self, month_str):
        """
        Determine the year for a given month.
        If month is in the past (relative to current date), use previous year.
        If month is current or future, use current year.
        
        Args:
            month_str: Month name or "All" for all months
            
        Returns:
            tuple: (month_number, year) or (None, None) for "All"
        """
        if month_str.lower() == 'all':
            return None, None

        months_map = {
            'january': 1, 'february': 2, 'march': 3, 'april': 4,
            'may': 5, 'june': 6, 'july': 7, 'august': 8,
            'september': 9, 'october': 10, 'november': 11, 'december': 12
        }

        month_num = months_map.get(month_str.lower())
        if month_num is None:
            raise ValueError(f"Invalid month: {month_str}")

        now = datetime.now()
        current_month = now.month
        current_year = now.year

        # If selected month is in the past, use previous year
        if month_num < current_month:
            year = current_year - 1
        else:
            year = current_year

        return month_num, year

    def generate_sales_report(self, month_str, username):
        """
        Generate sales report PDF.
        
        Args:
            month_str: Month name or "All"
            username: Username for logging
            
        Returns:
            BytesIO: PDF buffer
        """
        conn = self.get_db_connection()
        cur = conn.cursor(dictionary=True)

        month_num, year = self.get_year_for_month(month_str)

        # Fetch data
        if month_num and year:
            # Single month
            cur.execute("""
                SELECT i.item_name, sh.quantity_sold, sh.month, sh.year
                FROM sales_history sh
                JOIN items i ON sh.item_id = i.item_id
                WHERE sh.month = %s AND sh.year = %s
                ORDER BY sh.quantity_sold DESC
            """, (month_num, year))
        else:
            # All months - group by month, create subtables
            cur.execute("""
                SELECT i.item_name, sh.quantity_sold, sh.month, sh.year
                FROM sales_history sh
                JOIN items i ON sh.item_id = i.item_id
                ORDER BY sh.year DESC, sh.month DESC, sh.quantity_sold DESC
            """)

        rows = cur.fetchall()
        cur.close()
        conn.close()

        # Create PDF
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.5*inch, bottomMargin=0.5*inch)
        story = []

        # Styles
        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=16,
            textColor=colors.HexColor('#059669'),
            spaceAfter=6,
            alignment=1
        )
        heading_style = ParagraphStyle(
            'CustomHeading',
            parent=styles['Heading2'],
            fontSize=12,
            textColor=colors.HexColor('#059669'),
            spaceAfter=4,
            alignment=0
        )

        # Title
        story.append(Paragraph(f"Sales Report - {month_str}", title_style))
        story.append(Paragraph(f"Generated by: {username} on {datetime.now().strftime('%Y-%m-%d %H:%M')}", styles['Normal']))
        story.append(Spacer(1, 0.2*inch))

        # Build table(s)
        if month_num and year:
            # Single month table
            if rows:
                table_data = [['Item Name', 'Quantity Sold']]
                total_qty = 0
                for r in rows:
                    table_data.append([r['item_name'], str(r['quantity_sold'])])
                    total_qty += r['quantity_sold']
                table_data.append(['TOTAL', str(total_qty)])

                table = Table(table_data, colWidths=[4*inch, 1.5*inch])
                table.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#059669')),
                    ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                    ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('FONTSIZE', (0, 0), (-1, 0), 11),
                    ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                    ('BACKGROUND', (0, -1), (-1, -1), colors.lightgrey),
                    ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'),
                    ('GRID', (0, 0), (-1, -1), 1, colors.black),
                    ('ROWBACKGROUNDS', (0, 1), (-1, -2), [colors.white, colors.HexColor('#f3f4f6')]),
                ]))
                story.append(table)
            else:
                story.append(Paragraph(f"No sales data for {month_str}.", styles['Normal']))

        else:
            # All months - group by month
            months_data = {}
            months_list = ['January', 'February', 'March', 'April', 'May', 'June',
                          'July', 'August', 'September', 'October', 'November', 'December']

            for r in rows:
                key = f"{months_list[r['month']-1]} {r['year']}"
                if key not in months_data:
                    months_data[key] = []
                months_data[key].append(r)

            for month_year, items in months_data.items():
                story.append(Paragraph(month_year, heading_style))

                table_data = [['Item Name', 'Quantity Sold']]
                total_qty = 0
                for item in items:
                    table_data.append([item['item_name'], str(item['quantity_sold'])])
                    total_qty += item['quantity_sold']
                table_data.append(['TOTAL', str(total_qty)])

                table = Table(table_data, colWidths=[4*inch, 1.5*inch])
                table.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#059669')),
                    ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                    ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('FONTSIZE', (0, 0), (-1, 0), 10),
                    ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
                    ('BACKGROUND', (0, -1), (-1, -1), colors.lightgrey),
                    ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'),
                    ('GRID', (0, 0), (-1, -1), 1, colors.black),
                    ('ROWBACKGROUNDS', (0, 1), (-1, -2), [colors.white, colors.HexColor('#f3f4f6')]),
                ]))
                story.append(table)
                story.append(Spacer(1, 0.3*inch))

        doc.build(story)
        buffer.seek(0)
        return buffer

    def generate_inventory_report(self, month_str, username):
        """
        Generate inventory report PDF (current inventory based on expire_date).
        
        Args:
            month_str: Month name (determines context year)
            username: Username for logging
            
        Returns:
            BytesIO: PDF buffer
        """
        conn = self.get_db_connection()
        cur = conn.cursor(dictionary=True)

        # Get year context from month
        month_num, year = self.get_year_for_month(month_str)

        # Fetch current inventory (non-expired items)
        cur.execute("""
            SELECT i.item_name, COALESCE(SUM(ib.stock_quantity), 0) as stock, MIN(ib.expire_date) as expire_date
            FROM items i
            LEFT JOIN inventory_batches ib ON i.item_id = ib.item_id
            WHERE ib.expire_date > CURDATE() OR ib.id IS NULL
            GROUP BY i.item_id
            ORDER BY stock DESC
        """)

        rows = cur.fetchall()
        cur.close()
        conn.close()

        # Create PDF
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.5*inch, bottomMargin=0.5*inch)
        story = []

        # Styles
        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=16,
            textColor=colors.HexColor('#059669'),
            spaceAfter=6,
            alignment=1
        )

        # Title
        story.append(Paragraph(f"Inventory Report - {month_str}", title_style))
        story.append(Paragraph(f"Generated by: {username} on {datetime.now().strftime('%Y-%m-%d %H:%M')}", styles['Normal']))
        story.append(Spacer(1, 0.2*inch))

        # Build table
        if rows:
            table_data = [['Item Name', 'Stock Quantity', 'Expire Date']]
            total_stock = 0
            for r in rows:
                expire_str = r['expire_date'].strftime('%Y-%m-%d') if r['expire_date'] else 'N/A'
                table_data.append([r['item_name'], str(r['stock']), expire_str])
                total_stock += r['stock']

            table_data.append(['TOTAL STOCK', str(total_stock), ''])

            table = Table(table_data, colWidths=[3.5*inch, 1.5*inch, 1.5*inch])
            table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#059669')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 11),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, -1), (-1, -1), colors.lightgrey),
                ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'),
                ('GRID', (0, 0), (-1, -1), 1, colors.black),
                ('ROWBACKGROUNDS', (0, 1), (-1, -2), [colors.white, colors.HexColor('#f3f4f6')]),
            ]))
            story.append(table)
        else:
            story.append(Paragraph("No inventory data available.", styles['Normal']))

        doc.build(story)
        buffer.seek(0)
        return buffer
